

let  laptops = [
  {
    "id": 10001,
    "make": "Dell",
    "model": "Latitude E5570",
    "resolution": "1920 x 1080",
    "cpu": "i5-6300HQ",
    "speed": "2.30 GHz",
    "ram": 16,
    "storage": "256 GB SSD",
    "gpu": "",
    "os": "Microsoft Windows 10 Pro",
    "notes": "Backlit keyboard",
    "screenSize": "15.6",
    "custom": false,
    "features": [],
    "connectivity": [],
    "price": 0,
    "color": "",
    "type": ""
  },
  {
    "id": 10002,
    "make": "HP",
    "model": "Elitebook 850 G2",
    "resolution": "1920 x 1080",
    "cpu": "i5-5200U",
    "speed": "2.20 GHz",
    "ram": 12,
    "storage": "256 GB SSD",
    "gpu": "",
    "os": "Microsoft Windows 10 Pro",
    "notes": "brand new battery",
    "screenSize": "14",
    "custom": true,
    "features": [],
    "connectivity": [],
    "price": 0,
    "color": ""
  },
  {
    "id": 10003,
    "make": "Mac",
    "model": "Latitude E5570",
    "resolution": "1920 x 1080",
    "cpu": "i5-6300HQ",
    "speed": "2.30 GHz",
    "ram": 16,
    "storage": "256 GB SSD",
    "gpu": "",
    "os": "Microsoft Windows 10 Pro",
    "notes": "Backlit keyboard",
    "screenSize": "15.6",
    "custom": false,
    "features": [],
    "connectivity": [],
    "price": 300
  },
  {
    "id": 10004,
    "make": "Razor",
    "model": "Elitebook 850 G2",
    "resolution": "1920 x 1080",
    "cpu": "i5-5200U",
    "speed": "2.20 GHz",
    "ram": 12,
    "storage": "256 GB SSD",
    "gpu": "",
    "os": "Microsoft Windows 10 Pro",
    "notes": "brand new battery",
    "screenSize": "14",
    "custom": true,
    "features": [],
    "connectivity": [],
    "price": 400
  }
  ];

  export default laptops